name: texpackhelper # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: git # just for humans, typically '1.2+git' or '1.3.2'
summary: Tools for working with neural network-enhanced video game textures. # 79 char long summary
description: |
  texpackhelper is designed to solve a set of issues that come from
  using neural networks for creating high-resolution video game texture
  packs from the original game files.

  Using neural networks such as waifu2x is becomming a popular way to
  breath new life into older games by upscaling those textures so that
  they look much better at higher resolutions. This process isn't perfect, 
  however, and could benefit from additional automation.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  texpackhelper:
    plugin: go
    source: https://github.com/iAmSomeone2/texpackhelper.git
    go-importpath: github.com/iAmSomeone2/texpackhelper
    source-type: git
    source-depth: 1
    source-branch: image
    build-packages: [
      libmagickwand-dev
    ]

apps:
  texpackhelper:
    command: bin/texpackhelper
  plugs: [
    :home
  ]
